### ISSUE TITLE
Add disclaimer/warning to existing CPE website

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-cp-platform#130]
#### Description
 - Create a pop/warning that the existing CPE website is not being updated with the latest data?
    - The NYC Capital Projects component of NYC DCP’s Capital Planning Explorer is no longer being updated with the latest data. To download the latest Capital Projects data, please refer to [NYC Open Data](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Projects/fi59-268w/about_data) or  [Bytes of the Big Apple](https://www.nyc.gov/site/planning/data-maps/open-data.page) . For a web map version of the same data,  please use [CDPB Explorer](https://experience.arcgis.com/experience/150ca77c6dff4b079b7e079764121afe). Please stay tuned for an updated and enhanced version of CPE.

**Comment by TylerMatteo** [comment]
@horatiorosa Thanks for taking initiative here I'm going to pull this out of the sprint until we have a clearer comms plan for this project.

**Comment by horatiorosa** [comment]
closing in favor of #132
